### ISSUE TITLE
Change GC rules to Junior Leaque

### ISSUE THREAD

**Issue by i-khokhlov** [RoboCupHSJL/GameController#1]

**Comment by kefir8888** [comment]
Kick-off

Гол не может быть забит сразу после начала игры. Мяч должен переместиться на 20 сантиметров от стартовой позиции или его должен коснуться игрок команды противника, прежде чем он может быть забит в ворота. Если гол был забит с первого удара, кик-офф отдаётся команде противника.

Перед началом игры роботы должны быть на своих половинах поля. Роботы команды, не начинающей игру, должны находиться за пределами центрального круга, пока мяч не был введён в игру касанием или не прошло 1- секунд с начала игры.

Роботы, которые могут локализоваться, могут занимать любую из разрешённых (на своей половине поля не в круге) позицию на поле. Роботы, который не может локализоваться, должен стартовать из точки (0, -0.4)




Удержание мяча

Удержание мяча - активный контакт с мячом на протяжении более чем 1 секунды. Вратарь может удерживать мяч на протяжении не более чем 5 секунд.



Продолжительность матча

Обычные таймы длятся по 3 минуты, в полуфинале и финале по 5 минут.

В игре на вылет к основному времени добавляются ещё 2 тайма по 3 минуты, если счёт равный. Если ни одна из команд не забила в основном времени, игра переходит в стадию пенальти без дополнительных таймов.

***Сейчас идёт обсуждение того, не сделать ли таймы в симуляции по 5 или 7 минут***
<img width="562" alt="Снимок экрана 2021-07-22 в 20 29 02" src="https://user-images.githubusercontent.com/5654990/126683030-56de1959-7294-4b5d-bab0-3ee05ce08c73.png">

**Comment by kefir8888** [comment]
- между тем, как робота забрали на обслуживание, и моментом, когда он снова может играть, должно пройти не меньше 60 секунд
- если более одного робота атакующей команды находится в области у ворот или в воротах оппонента больше, чем 10 секунд, его атака считается неправомерной. Тот же критерий применяется к роботам защищающейся команды
- на пенальти даётся 60 секунд
- продолжительность тайм-аута - 120 секунд
- ситуация, при которой в игре нет прогресса в течение 60 секунд, называется game-stuck situation и приводит к "выбрасыванию мяча" (dropped ball), что то же самое, что kick-off, только роботы обеих команд находятся вне центрального круга

**Comment by i-khokhlov** [comment]
https://github.com/RoboCupHSJL/GameController/blob/56c21be785fdfe8bcd9cb32be71dccd414fc87d3/src/data/hl/HLSim.java#L17-L123

**Comment by i-khokhlov** [comment]
https://github.com/RoboCupHSJL/GameController/blob/add-junior-league/src/data/hl/HLSimulationJunior.java
